{{- if eq .Values.stalwart.storage.backend "postgres" }}
{{- if not .Values.stalwart.storage.postgres.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "stalwart.fullname" . }}-db
  labels:
    {{- include "stalwart.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.stalwart.storage.postgres.secretUserKey }}: {{ .Values.stalwart.storage.postgres.user | quote }}
  {{ .Values.stalwart.storage.postgres.secretDatabaseKey }}: {{ .Values.stalwart.storage.postgres.database | quote }}
  {{ .Values.stalwart.storage.postgres.secretPasswordKey }}: {{ required "stalwart.storage.postgres.password is required when no existingSecret is set" .Values.stalwart.storage.postgres.password | quote }}
{{- end }}
{{- end }}
{{- if and (eq .Values.stalwart.storage.blobBackend "s3") (not .Values.stalwart.storage.s3.existingSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "stalwart.fullname" . }}-s3
  labels:
    {{- include "stalwart.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.stalwart.storage.s3.secretAccessKeyKey }}: {{ required "stalwart.storage.s3.accessKey is required when no existingSecret is set" .Values.stalwart.storage.s3.accessKey | quote }}
  {{ .Values.stalwart.storage.s3.secretSecretKeyKey }}: {{ required "stalwart.storage.s3.secretKey is required when no existingSecret is set" .Values.stalwart.storage.s3.secretKey | quote }}
{{- end }}
