{{- if .Values.webmail.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "stalwart.fullname" . }}-webmail
  labels:
    {{- include "stalwart.webmail.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.webmail.replicas }}
  revisionHistoryLimit: {{ .Values.webmail.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "stalwart.webmail.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.webmail.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "stalwart.webmail.selectorLabels" . | nindent 8 }}
    spec:
      automountServiceAccountToken: false
      securityContext:
        {{- toYaml .Values.webmail.podSecurityContext | nindent 8 }}
      {{- with .Values.webmail.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.webmail.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: snappymail
          image: "{{ .Values.webmail.image.repository }}:{{ .Values.webmail.image.tag }}"
          imagePullPolicy: {{ .Values.webmail.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.webmail.securityContext | nindent 12 }}
          ports:
            - name: http
              containerPort: {{ .Values.webmail.service.port }}
              protocol: TCP
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: snappymail-data
              mountPath: /var/lib/snappymail
            - name: php-fpm-conf
              mountPath: /usr/local/etc/php-fpm.d
            - name: php-run
              mountPath: /run
          {{- with .Values.webmail.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: tmp
          emptyDir: {}
        - name: snappymail-data
          emptyDir: {}
        - name: php-fpm-conf
          emptyDir: {}
        - name: php-run
          emptyDir: {}
      {{- with .Values.webmail.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.webmail.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.webmail.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "stalwart.fullname" . }}-webmail
  labels:
    {{- include "stalwart.webmail.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "stalwart.webmail.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.webmail.service.port }}
      targetPort: http
      protocol: TCP
{{- end }}
